### ISSUE TITLE
One piece case please 

### ISSUE THREAD

**Issue by tangbonze** [SylivanKenobi/t-rex#1]
Could you please share one piece case file? Thanks a lot.

**Comment by SylivanKenobi** [comment]
Yeah i will do this probably this weekend

**Comment by tangbonze** [comment]
Thank you！

**Comment by SylivanKenobi** [comment]
I added it:
https://github.com/SylivanKenobi/t-rex/blob/main/cases/closed-falt-case/regular-closed.stl
