### ISSUE TITLE
WS2812B support 

### ISSUE THREAD

**Issue by iamagithublearner** [SylivanKenobi/t-rex#2]
Hey can you please help me with configuring the WS2812B leds? where do i start?

**Comment by SylivanKenobi** [comment]
Yeah sure I just start at the beginning. There are three holes on the left side of the board. The square one is data, middle is ground and the other is power. In the t-rex firmware the leds are enabled by  default. You have to configure the amount of leds that you install [here](https://github.com/SylivanKenobi/qmk_firmware/blob/343a26f16749af895945b1a97527ff421265a8eb/keyboards/t_rex/info.json#L28) . Everything for the leds can be configured in the [info.json](https://github.com/SylivanKenobi/qmk_firmware/blob/master/keyboards/t_rex/info.json) you can find the qmk docs for it [here](https://github.com/qmk/qmk_firmware/blob/master/docs/reference_info_json.md#rgb-lighting). Does this answer your questions or do you need something more specific?

**Comment by SylivanKenobi** [comment]
I close this Issue as there was no further input for two weeks.
