### ISSUE TITLE
Minimal Case

### ISSUE THREAD

**Issue by AbhinashPatro** [SylivanKenobi/t-rex#3]
Hi Sylivan, How do you mount pcb to the case though ? Your PCB Gerber files contain no holes on the PCB but the picture of the back of the PCB shows the holes for passing the standoff. I am little confused on this .

**Comment by SylivanKenobi** [comment]
This is a mistake. It looks like in the process of updating to kicad 7 the holes for the case mounting got lost. I will fix this today.

**Comment by SylivanKenobi** [comment]
The holes are back. [This commit](https://github.com/SylivanKenobi/t-rex/commit/68a8e1d2b7005a494b37ec6a024ebed064c535c4) fixes this.

**Comment by AbhinashPatro** [comment]
Thanks for fixing the bug
